### ISSUE TITLE
Misspelled reference

### ISSUE THREAD

**Issue by matsievskiysv** [hplgit/fem-book#14]
There's a misspelled reference on page 10:
![image](https://user-images.githubusercontent.com/26824900/103178198-c22b2f80-4891-11eb-8f3a-2257f7ff27a9.png)

**Comment by kent-and** [comment]
Which version is this? I think this has been fixed already?

**Comment by matsievskiysv** [comment]
Yes, looks like it. Sorry, I think I've got the link somewhere from Fenics site.
