### ISSUE TITLE
Vector missing line break

### ISSUE THREAD

**Issue by matsievskiysv** [hplgit/fem-book#17]
On page 64 there's a missing linebreak in the vector `c`:
![image](https://user-images.githubusercontent.com/26824900/108637451-cb083e00-749b-11eb-8084-5349e53c5268.png)
`fem-book/doc/.src/book/dotxt/approx.do.txt`:
![image](https://user-images.githubusercontent.com/26824900/108637523-1589ba80-749c-11eb-887b-c9afc893c9be.png)

**Comment by kent-and** [comment]
thanks!
fixed now
